// Mocks generated by Mockito 5.0.10 from annotations
// in mybudget/test/controller/initial_controller_test.dart.
// Do not manually edit this file.

import 'package:mockito/mockito.dart' as _i1;
import 'package:mybudget/repository/monthly_repository.dart' as _i3;
import 'package:mybudget/repository/settings_repository.dart' as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [SettingsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsRepository extends _i1.Mock
    implements _i2.SettingsRepository {
  MockSettingsRepository() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [MonthlySummaryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMonthlySummaryRepository extends _i1.Mock
    implements _i3.MonthlySummaryRepository {
  MockMonthlySummaryRepository() {
    _i1.throwOnMissingStub(this);
  }
}
